name: chargemod
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  permission_handler: ^11.1.0
  http: 1.1.2
  country_code_picker: ^3.0.0
  flutter_svg: 2.0.9
  url_launcher: ^6.2.0
  android_intent_plus: ^4.0.3
  sms_autofill: ^2.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1



flutter:
  uses-material-design: true
  assets:
    - images/

#  fonts:
#    - family: HarmoniaSansProCyrillic
#      fonts:
#        - asset: fonts/HarmoniaSansProCyrillic-Regular.ttf
#          weight: 400

